all: 
		cd 1b/ && make all
		cd 2a/ && make all
		cd 2b/ && make all
		cd 2c/ && make all

clean:
		cd 1b/ && make clean
		cd 2a/ && make clean
		cd 2b/ && make clean
		cd 2c/ && make clean

cleanall:
		cd 1b/ && make cleanall
		cd 2a/ && make cleanall
		cd 2b/ && make cleanall
		cd 2c/ && make cleanall

run:
		cd 1b/ && make run
		cd 2a/ && make run
		cd 2b/ && make run
		cd 2c/ && make run

